### ISSUE TITLE
No progress?

### ISSUE THREAD

**Issue by ErikKrause** [firephp/firephp-for-firefox-devtools#1]
Why is there no progress?

**Comment by cadorn** [comment]
Because I have a paid job.

**Comment by cadorn** [comment]
That being said. I have been busy and expect to have some big releases very soon.

**Comment by Sogl** [comment]
Really need a new version. I use hacks in `about:config` to bring old Firebug/Firephp to life in FF 51.

**Comment by Patabugen** [comment]
Hey @cadorn - I'm up for helping to develop this if you're ready for contributors.

**Comment by cadorn** [comment]
I have a prototype working. I am going to try and push something for first review soon.

**Comment by powtac** [comment]
@Sogl how can one activate FirePHP via about:config again?

**Comment by ErikKrause** [comment]
You'd need to disable E10s, however, this won't revive Firebug completely, since other parts have also changed. Until new FirePHP is ready (if ever) use my fork of ChromePHP, which can act as a drop-in replacement for FirePHP working with native Firefox Devtools: https://github.com/ErikKrause/chromephp

**Comment by powtac** [comment]
Ah! ChromePHP is a Firefox Devtools compatible protocol that is native understandable by the Firefox Devtools without special Extension! Am i correct?

**Comment by cadorn** [comment]
FYI, I am making progress. After I finish https://github.com/jsonrep/jsonrep (the object rendering pulled out into its own project) I will be focusing on the extension.

**Comment by powtac** [comment]
Offtopic: google . com did expose data with Firebug activated. Nothing serious but server instance name and similar.

**Comment by ErikKrause** [comment]
Seems it is more urgent than ever. There are rumors that ChromPHP will cease to work in FF 55  (which would be a shame btw.)

**Comment by powtac** [comment]
<img src="https://media.giphy.com/media/ULyYV5amK2eYM/giphy.gif">

**Comment by ErikKrause** [comment]
Well, seems more like a storm in a teacup: I tried FF 55.0b14 and ChromePHP works perfectly there.

**Comment by cadorn** [comment]
I am part way done with the basic FirePHP Core functionality in the extension. I'll be away for two weeks and will then try to make regular progress in time for the Firefox 57 update.

**Comment by cadorn** [comment]
Good news! I have a first prototype working: https://github.com/firephp/firephp-for-firefox-devtools/raw/master/dist/firephp.xpi

It will add a devtools panel and should work with the FirePHPCore library. It is still rough. More to come.

It would be nice to find out if it works for others by checking if logging using FirePHPCore on the server to the FirePHP panel in Firefox works.

**Comment by cadorn** [comment]
This is what it should look like:

<img width="822" alt="screen shot 2017-11-06 at 12 42 36 am" src="https://user-images.githubusercontent.com/18679/32432288-d1ef9012-c28b-11e7-8bce-ac851f223346.png">

**Comment by ngocphamm** [comment]
Accessing firephp.org shows me similar result. However from a Joomla page with some basic FirePHP logging, it does not show anything. The response's header does not contain any FirePHP info as it should.

That same Joomla page still shows the log in Chrome with FirePHP4Chrome extension installed.

**Comment by cadorn** [comment]
Pushed update: https://github.com/firephp/firephp-for-firefox-devtools/raw/master/dist/firephp.xpi

Fixes: #5, #7 

@ErikKrause Please try again. Feel free to post other feedback/wishes.

@ngocphamm If you can assist can you file new issue with request headers sent by * FirePHP4Chrome* and *FirePHP* so I can compare. Other than not sending the correct header I am not sure what could be wrong.

**Comment by ngocphamm** [comment]
Yay it works now if I check both the checkboxes for "Enable UserAgent Header" and "Enable FirePHP Header" in the FirePHP panel!

I notice the request being sent to server is added with header `X-FirePHP-Version: 0.4`, then the response comes back with all the `X-Wf-...` stuff.

However, I still see the logs being cleared whenever another tab is reloaded. Basically if I have multiple tabs with all having FirePHP logs, I will only be able to see one.

**Comment by ngocphamm** [comment]
And... Firefox Developer Edition got an update today to a 58.0b1 then things stopped working.

This is not a complaint. Just a heads up. Thanks for your hard work on this @cadorn

**Comment by ErikKrause** [comment]
Works perfectly here on 58. You must disable and enable FirePHP haders to make it work. See issue #10...

**Comment by ngocphamm** [comment]
Oh yeah my bad... Didn't try that. Thanks @ErikKrause

**Comment by cadorn** [comment]
New build: https://github.com/firephp/firephp-for-firefox-devtools/raw/master/dist/firephp.xpi

Should fix all tab switching/reloading issues.

**Comment by cadorn** [comment]
There is a new build. I am now tracking builds/releases on the wiki homepage: https://github.com/firephp/firephp-for-firefox-devtools/wiki

In the next week I hope to complete some of the important issues and get the extension up on the mozilla addons site.

Thank you for your feedback on the initial releases. I look forward to more bug reports and feature requests.

**Comment by frankforte** [comment]
Hi Christoph

FirePHP made my life a lot better. I released QuantumPHP in a rush to get things working on Firefox 57, but my web extension is not so great. Any chance we can collaborate? I'm hoping to get the QuantumPHP server code working with the FirePHP web extension. https://github.com/frankforte/quantumphp

Cheers
Frank

**Comment by cadorn** [comment]
> Any chance we can collaborate? I'm hoping to get the QuantumPHP server code working with the FirePHP web extension. 

@frankforte Sure! You will be able to build the extension yourself once I finish [1].

Feel free to propose what you want to do exactly in a new issue and we can discuss.

[1] - https://github.com/firephp/firephp-for-firefox-devtools/issues/37
