### ISSUE TITLE
FirePHP pane should stay visible on tab change

### ISSUE THREAD

**Issue by ErikKrause** [firephp/firephp-for-firefox-devtools#12]
In devtools detached mode, if I change to another tab the FirePHP pane is currently emptied and populated again once I go back to the tab where the relevant page is open. It would be nice if the content would stay visible like the other devtools panes do. Not very important , though.

**Comment by cadorn** [comment]
Does it work properly in latest build?: https://github.com/firephp/firephp-for-firefox-devtools/raw/master/dist/firephp.xpi

**Comment by ErikKrause** [comment]
Unfortunately not. The only thing that changed is that there is no details view in the right pane any more.

**Comment by cadorn** [comment]
Ah, yes. This should fix it **Pin panel context to tab if devtools detached**: https://github.com/firephp/firephp-for-firefox-devtools/issues/28

There will also be **Persist logs on navigate option**: https://github.com/firephp/firephp-for-firefox-devtools/issues/22

The other issues is with multiple windows: https://github.com/firephp/firephp-for-firefox-devtools/issues/27

I am closing this as I think it will be solved with above.
