### ISSUE TITLE
coloring 

### ISSUE THREAD

**Issue by ErikKrause** [firephp/firephp-for-firefox-devtools#13]
The current coloring is hard to read. Different background colors are not good, neither is grey on white. I'd prefer a coloring like the firebug or the old devtools console. FirePHP also doesn't respect the devtools theme.

**Comment by ErikKrause** [comment]
With "Different background colors" I mean the labels (I use them exclusively to name variables). Different background for Log, Info, Warn etc is perfectly ok. It would be nice to display the labels in the right pane as well.

**Comment by cadorn** [comment]
Split into:

  * Respect devtools theme - https://github.com/firephp/firephp-for-firefox-devtools/issues/16
  * Bring back firebug coloring - https://github.com/firephp/firephp-for-firefox-devtools/issues/17
  * Display label in right pane - https://github.com/firephp/firephp-for-firefox-devtools/issues/18
  * Make colour scheme for logging configurable - https://github.com/firephp/firephp-for-firefox-devtools/issues/19
