### ISSUE TITLE
FirePHP tab does not appear in devtools

### ISSUE THREAD

**Issue by tylla** [firephp/firephp-for-firefox-devtools#15]
I installed the extension from the link mentioned in #1, but there is no FirePHP tab in the developer tools. I tried to restart Firefox, disable/re-enable the extension but nothing.
I'm using Firefox v: 52.4.0 64 bit on Linux (Debian Jessie).

Any ideas what am I doing wrong?

**Comment by cadorn** [comment]
Is the extension listed as an installed addon in the browser?

Also check the **Developer Tools -> Browser Console** for errors that could be related.

**Comment by cadorn** [comment]
You can try the latest build: https://github.com/firephp/firephp-for-firefox-devtools/raw/master/dist/firephp.xpi

Also try firefox beta/developer edition if you cannot see any errors.

**Comment by tylla** [comment]
Thanks for the help.
The extension is listed as installed.
With the previous version (that was installed when I posted the ticket) there was only one line repeating:
> WARNING Error: Could not establish connection. Receiving end does not exist.  background.js:6025:9
After that I removed and installed the latest version, now there are other console messages too (like "tabs.onActivated" and "Domain settings for...") and the warnings like above. 
But no errors from the firephp extension.

The beta/dev version is a good idea I will give it a try.

**Comment by cadorn** [comment]
Sometimes when I open devtools and switch to the panel the UI is empty (and no errors) and I have to close devtools and open again for the **Reload to init** message to show at which point you can reload the page and everything works (https://github.com/firephp/firephp-for-firefox-devtools/issues/26). Maybe that is similar to your issue now.

If it does not work on the other Firefox releases and with the above suggestion I am going to try it myself and go from there.

**Comment by cadorn** [comment]
This may be fixed in the new build: https://github.com/firephp/firephp-for-firefox-devtools/pull/39
