### ISSUE TITLE
FirePHP logs too little.

### ISSUE THREAD

**Issue by ErikKrause** [firephp/firephp-for-firefox-devtools#23]
Hello,

if I use my chromelogger fork I get 42 entries. If I use the very same page with FirePHP I get only 8 entries.
![zwischenablage01](https://user-images.githubusercontent.com/6303830/32673888-16b9da86-c651-11e7-8c91-db09d2f3de80.jpg)
![zwischenablage02](https://user-images.githubusercontent.com/6303830/32673925-454e3d06-c651-11e7-943e-8d003145f0be.jpg)

**Comment by ErikKrause** [comment]
Well, I might have an idea where this comes from. The first 8 entries are from the page itself, the other entries are from http requests from the page as f.e. images (there is a php image handler). But why doesn't FirePHP display those?

**Comment by cadorn** [comment]
I am not currently including them but they will start working: https://github.com/firephp/firephp-for-firefox-devtools/issues/25
