### ISSUE TITLE
FirePHP shows always FirePHP.class.php instead of actual file

### ISSUE THREAD

**Issue by ErikKrause** [firephp/firephp-for-firefox-devtools#24]
If I expand an entry clicking the + button in the top riht corner of the entry there is a file name and line number shown. I assume this should be the name and line where the message was logged. However, it is always the same line and file. This happens on my local page but not on firephp.org. Do I have the wrong server version? This version used to work in firebug.
![zwischenablage03](https://user-images.githubusercontent.com/6303830/32674156-697c8736-c652-11e7-8c8b-167b8c7967ab.jpg)

**Comment by cadorn** [comment]
If I recall correctly this can happen if you do not call the FirePHP methods directly. You may need to patch the FirePHPCore class to exclude more paths. I have plans to expand the API in FirePHPCore to make that easier in time.

**Comment by ErikKrause** [comment]
I do the following to initialize:
```
require_once($include_dir."FirePHP.class.php");
$firephp = FirePhp::getInstance(true);
$firephp->setEnabled(true);
```
and later I do f.e.:
```
$firephp->log($GeoCountry, '$GeoCountry -ci');
$firephp->log($_GET, '$_GET -ci');
```
The calls in this project haven't changed for ages and they worked well in Firebug. I also tried various versions of FirePHP.class.php to no avail.

**Comment by cadorn** [comment]
Hmm, not sure. The path is provided by the server so you will see it in the HTTP response headers.

You can try the path filter feature when it becomes available: https://github.com/firephp/firephp-core/issues/41

**Comment by ErikKrause** [comment]
You are right, the wrong path was in the HTTP headers. I changed the line
`|| substr($this->_standardizePath($trace[$i]['file']),-29,29)=='FirePHPCore/FirePHP.class.php')) {
`
to 
`|| substr($this->_standardizePath($trace[$i]['file']), -17, 17) == 'FirePHP.class.php')) {`
in FirePHP.class.php (since I don't have it in a folder named FirePHPCore). Now it works. 

The strange thing is: The line with FirePHPCore in it is in all older versions of that file I have used starting with v0.3 in at least 20 projects and all of them worked with firebug. The only thing I changed since I stopped using firebug was the PHP version (from 5.2 to 5.6). Could that be the reason?

**Comment by cadorn** [comment]
No idea. I'll check into all this when I look at FirePHPCore.

Continued here: https://github.com/firephp/firephp-core/issues/41
