### ISSUE TITLE
Enable logging for sub-requests

### ISSUE THREAD

**Issue by cadorn** [firephp/firephp-for-firefox-devtools#25]
Only logs from the page request currently show.

Include logs from image/JS/ajax etc... requests.

Ensure this works when requests are re-played as well. See: https://github.com/firephp/firephp-core/issues/38

**Comment by ErikKrause** [comment]
Interestingly I saw the logs from sub-requests once but they where gone on page reload. It happens sometimes if I follow a link and sometimes it flashes only and disappears.
![grafik](https://user-images.githubusercontent.com/6303830/32701016-b8dcd43e-c7ce-11e7-8032-88fb515a007e.png)
