### ISSUE TITLE
Strange behavior on pages with embedded content.

### ISSUE THREAD

**Issue by ErikKrause** [firephp/firephp-for-firefox-devtools#32]
If I load a page with embedded content (iframes in this case), the log shows for a split second, then the "Manage" page flashes for player.vimeo.com or youtube.com, for facebook.com and even for about:blank. Then it stays blank.

**Comment by ErikKrause** [comment]
Sorry, this is not fixed completely. If I load a page with static iframes the settings  page flashes for any of the embedded URLs but the final display is the logs. This is fine (although the flashing is a bit distracting). However, if I load a page (same domain) in a lightbox (fancybox in this case) which is displayed in an iframe dynamically, the log page goes blank and stays so no matter whether I follow a link in the lightbox (load another page) or not. When the lightbox is closed the FirePHP tab shows the settings page for about:blank.
I'd expect to see the logs of the page loaded into the iframe. My chromelogger fork does this correctly and the firebug version did as well.

**Comment by ErikKrause** [comment]
I'm currently testing on a long time project with dozens of FirePHP calls in all files. The scenario is like this: On a normal page there are links which open a javascript lightbox. The lightbox script injects an iframe into the body element. The iframe loads a document from the same domain also containing FirePHP calls (I always use `$firephp->log(...`). 

If I watch all this on Network tab I can see the X-Wf-headers for FirePHP, but they don't show up on FirePHP tab. BTW.: The pages shown in the lightbox can also be opened directly, in which case the FirePHP logs display fine.

**Comment by cadorn** [comment]
Headers from embedded content should be handled much better in this new build: https://github.com/firephp/firephp-for-firefox-devtools/pull/39

Could you see if it all works now?

**Comment by stSaHiB** [comment]
I'm not 100% sure if thats the same problem, but I had an issue with ckeditor v3. If it was embedded in a page, outputs in firephp panel showed up for a few ms, the disappered. Only with activated persist setting (which needed to be activated on a page withou ckeditor) messages in panel showed up.
BUT: with the new preview version this issue is solved. Works smooth now...

**Comment by cadorn** [comment]
Good to hear this issue is solved. :)

> I'm not 100% sure if thats the same problem, but I had an issue with ckeditor v3.

That seems to be a bug in the new context system.
I suspect because it loads content from a different origin than the browser page?

Is there a page I can visit to test this?

**Comment by stSaHiB** [comment]
I was wrong, of course its ckEditor v4 :-)

I made you a sample:
http://popplers.de/firephp/

Its a kind of tricky to get FirePHP working here. Once cke has hidden the fb output you need to reload the page hitting the persist button while cke is not yet loaded and then reload. May take several aproches :-) Once it was hidden, it stays hidden even with persit on after reload. you have to turn persist off and on ist in the right moment... hard to explain - you'll see.

BUT in current refactor-version it works like a charm.

**Comment by cadorn** [comment]
> BUT in current refactor-version it works like a charm.

Ah, ok, I mis-understood. So all is good now.

I tried out the sample you put up. Works well. So cool to enable debugging on someone else's server and get debug messages back!
