### ISSUE TITLE
Accented characters are not properly handled

### ISSUE THREAD

**Issue by albanc26** [firephp/firephp-for-firefox-devtools#38]
Hello,

First a big thank you for the new nice extension for Firefox Dev browser, and for all your work on firePHP.

I have just discovered the existence of firePHP and I am using it in conjunction with Monolog. It is great.

But i am facing the following issue :

In my file log on the server (streamHandler), accented characters are showing up properly.

But in firePHP, they are showing corrupted (see the screenshot below). My application is all utf-8 at every level and I've been working on it with multiple languages for 4 years, so I am pretty sure everything is fine with it on the utf8 side.

My issue seems related to this one : https://github.com/firephp/firephp/issues/16

![firephp](https://user-images.githubusercontent.com/26873653/35271715-438c122e-0033-11e8-8d1e-75ddbfe67e1a.jpg)

Best regards

**Comment by cadorn** [comment]
I am happy to hear you like the new FirePHP. I have big plans for it this year and I always welcome feedback no matter how trivial it is. I hope to finish some changes soon that will enable it to become a listed addon.

Regarding your issue. Look for the string in the response headers. If it is correct there it is an issue in the UI of FirePHP.

Can you post a sample string and screenshots of what is should look like and what FirePHP shows. I looked through the linked issues but never saw such a summary.

**Comment by albanc26** [comment]
Hello Cadorn,

Thank you for your feedback and sorry for the late answer, I have been overwhelmed lately + I couldn't get firePHP headers displayed using my traditional tools until I figured Firefox dev was showing them very effectively.

Here are the headers output. As you can see the garbage characters are present in the headers so, as you said, this excludes an issue in the issue of the FirePHP UI : 

![headers](https://user-images.githubusercontent.com/26873653/36093025-9aa5899e-0fe9-11e8-800b-5d3312893037.jpg)

I made sure my Nginx server was sending utf-8 by default by adding a ``charset utf-8;`` directive in nginx.conf.
I have also made sure my json PHP file was sending a correct utf-8 header by setting a ``header('Content-type: application/json; charset=utf-8');`` in the https://dyntest1.velorizons.com/mf/core/ajax-core-json.php file.
The texts featuring garbage characters are all set into utf-8 encoded files and would show properly outside of firePHP (for example by doing a PHP echo).

So my guess is there could be an encoding management problem at the firePHP level where the line is generated : 
``x-wf-1-1-1-16: 105|[{"Type":"INFO","File":"","Line":"","Label":"Mindflow_1112135546"},"CrÃ©ation du type de plugin backend"]|``

**Comment by cadorn** [comment]
This is working in latest release using the latest FirePHPCore server library: https://github.com/firephp/firephp-for-firefox-devtools/pull/39
