### ISSUE TITLE
Objects not showing in RefactorPreview

### ISSUE THREAD

**Issue by stSaHiB** [firephp/firephp-for-firefox-devtools#40]
Hi Christoph,

seeing this project is still alive made my day - THANK YOU!!!
I love all the changes you made so far, but I have one problem. If I want to debug an object, firephp crashes - not showing any further outputs.

Example:
`FB::warn($foo->bar(),'shows up in panel');`
`FB::warn($foo,'is not displayed in panel');`
`FB::warn($foo->bar(),'is now also not displayed in panel');`

I hope you can solve the issue. 

thumbs up for (in my opinion) the best debugging tool for PHP ;-)
Greetings
sahib

**Comment by cadorn** [comment]
> seeing this project is still alive made my day - THANK YOU!!!

That is nice to hear! 😄 Thanks for sharing.

>  debug an object, firephp crashes

Should be fixed in next release.

> thumbs up for (in my opinion) the best debugging tool for PHP ;-)

👍
