### ISSUE TITLE
Formatting integers

### ISSUE THREAD

**Issue by stSaHiB** [firephp/firephp-for-firefox-devtools#41]
Hi,

just a small thing: numbers are formated on output.
Example:
`'REQUEST_TIME'=>1,563,649,736`
This is nice to read, but a pain if you want to copy paste the number.

Also its alsways in the english format, while here in germany we format the above number like 1.563.649.736, so it's also hard to read. Beside that this is a unix timestamp, which does not need any formatting in my opinion :-)

So maybe an option for turning number formatting on and off? 
Or displaying the raw number in brackets? 
Or displaying the raw number on mouseover (so copy paste would be fine)
Or just no formatting at all...

Thx alot
sahib

**Comment by cadorn** [comment]
Makes sense. I think I will leave them unformatted for now. I have plans to add more formatting features via various mechanisms.

**Comment by cadorn** [comment]
Will show plain numbers in next release.
