### ISSUE TITLE
Page reload on init

### ISSUE THREAD

**Issue by stSaHiB** [firephp/firephp-for-firefox-devtools#42]
Hi Cristoph,

one thing which troubles me sometimes, with the new version, is that you are reloading the page when the enable button is activated.
I sometimes wan't to debug a form, filling it out, then realizing that FB isn't enabled - so what now? If I enable it, the form reloads, input is gone... If I dont enable it, I can't debug what's happening after I send it. Or I've just sended a form and I want to start debugging now, I first have to navigate somewhere else, so the form doesn't get reloaded, doing some suff I don't wan't to get done twice :-)

As for me I would prefer the old solution: after enabling, debugging starts after the next (manual) page relaod.

I see that the current versions is very charming for those users that are new to FB and wonder that nothing is happening after they enabled it. Automatic reload helps them to get that direct response to their action: "wow, I can debug to console, FirePHP is sooo cool!"
So maybe a checkbox in the settings panel is the solution? "reload page on enable" which is checked by default.

This has a rather poor priority, but when you are coding other options for the settings panel, maybe you find the time for it ;-)

Thx for all your effords

regards
sahib

**Comment by cadorn** [comment]
I have been wondering about this and was planning on adding a setting anyway.

There is a setting in the latest release: https://github.com/firephp/firephp-for-firefox-devtools/pull/39#issuecomment-515662829
