### ISSUE TITLE
Unable to get extension working in Chrome/Chromium

### ISSUE THREAD

**Issue by porl** [firephp/firephp-for-firefox-devtools#68]
Installed and reloaded browser. Load up a page with the extension and am asked to reload the page (can do so by clicking link in extension's devtools window). After this I get the message:

```
You must grant FirePHP permission to intercept requests.
Click on the FirePHP icon in the address bar.
```

No icon appears in the address bar. Tested on local (symfony based) site as well as http://firephp.org/.

Running Chromium Version 87.0.4280.88 (Official Build) Arch Linux (64-bit).

**Comment by stSaHiB** [comment]
got the current version of chromium running (Version 89.0.4361.0 on windows) - firephp is working as expected.
Look for the FirePHP icon right next to the adressbar, where all the other extensions are placed:

![grafik](https://user-images.githubusercontent.com/761264/102702681-9bec0b00-4265-11eb-815d-d6eb869cdd99.png)

**Comment by porl** [comment]
Thank you, the extension icon was in the overflow menu so I missed it. Perhaps the wording could be a little better - it is requesting to click the icon in the address bar, which is where you would see the bookmark star, zoom icon etc. Either way it is now functioning for me, thank you!

**Comment by cadorn** [comment]
@porl Good to hear you got it working. Thanks for the suggestion! https://github.com/firephp/firephp-for-browser-devtools/issues/69

Thanks @stSaHiB
