### ISSUE TITLE
Line numbers point to the wrong script

### ISSUE THREAD

**Issue by stSaHiB** [firephp/firephp-for-firefox-devtools#71]
hi,

I'm quite sure it was working a while ago as intended, but with my current version (1.5.7) I get the line number of the fb.php script:
![grafik](https://user-images.githubusercontent.com/761264/121776215-e94d9300-cb8b-11eb-84a1-db6a01d6c43e.png)
As you can see, that's quite useless as **all** calls get the same line number (fb.php @ 218 - at least for the warnings :-) instead of the line number of the actuall script that called the fb::warn().

Problem is in firefox as well as in chromium.

thx a lot
sahib

**Comment by cadorn** [comment]
Are you wrapping the FB logging functions in your own helper function?

The line numbers get added here: https://github.com/firephp/firephp-core/blob/master/lib/FirePHPCore/FirePHP.class.php#L1206-L1229

If the offset is wrong (typically due to wrapping the logging functions in your own helper functions) it can be adjusted using the `lineNumberOffset` option:

```
FirePHP::getInstance(true)->setOption('lineNumberOffset', 1);
```

**Comment by stSaHiB** [comment]
shame on me - it's not firePHP-BrowserExtensions fault, but it is a change in the FirePHP.class.php file you mentioned. 
I Checked it out in an old programm, the whole includeLineNumbers-Part is rewritten, which is resulting in the problem, mentioned above, when you use the static functions in FB class like I do:
`FB::warn('foo');`

Small remark about that: both versions I use, got `const VERSION='0.3';` still they are different. Looking at the git repo I see, the current Version is 0.5.3 - still having that 0.3 const in Code :-)

In any case: `lineNumberOffset ` option solves the problem! thx for fast help!!!!

**Comment by cadorn** [comment]
Are you saying that calling `FB::warn('foo');` will result in the wrong line numbers? That sounds like a regression.

I'll bump `const VERSION` in the next release.

**Comment by stSaHiB** [comment]
checked it out again: this time with 0.5.3 for sure, without `lineNumberOffset `, line number of  `FB::warn('foo');` will point to fb class, instead of the actuall call. With that `lineNumberOffset ` its easy to fix, but for someone not knowing that parameter it might be confusing. But for me: problem solved ;-)
